In [2]:
!pip install mlx

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 34.9 MB/s eta 0:00:00a 0:00:01


In [4]:
!python -c "import platform; print(platform.processor())"

arm


In [1]:
import mlx.core as mx
a = mx.array([1,2,3,4])
a.shape

(4,)

In [2]:
a.dtype

mlx.core.int32

In [3]:
b = mx.array([1.0,2.0,3.0,4.0])
b.dtype

mlx.core.float32

In [4]:
c = a + b
mx.eval(c)

In [5]:
c = a + b
print(c)

array([2, 4, 6, 8], dtype=float32)


In [6]:
c = a + b
import numpy as np
np.array(c)

array([2., 4., 6., 8.], dtype=float32)

In [7]:
x = mx.array(0.0)
mx.sin(x)

array(0, dtype=float32)

In [8]:
mx.grad(mx.sin)(x)

array(1, dtype=float32)

In [9]:
mx.grad(mx.grad(mx.sin))(x)

array(-0, dtype=float32)

In [11]:
a = mx.random.normal((100,))
b = mx.random.normal((100,))

In [12]:
mx.add(a, b, stream=mx.cpu)
mx.add(a, b, stream=mx.gpu)

array([-1.58656, 2.4869, -0.156394, ..., -1.45473, 2.31957, -2.61522], dtype=float32)

In [13]:
c = mx.add(a, b, stream=mx.cpu)
d = mx.add(a, c, stream=mx.gpu)

In [ ]:

def fun(a, b, d1, d2):
    x = mx.matmul(a, b, stream=d1)
    for _ in range(500):
        b = mx.exp(b, stream=d2)
    return x, b

In [27]:
a = mx.random.uniform(shape=(409600, 51200))
b = mx.random.uniform(shape=(51200, 400))

In [30]:
import timeit, time
start = time.perf_counter()

fun(a, b, mx.gpu, mx.gpu)

end = time.perf_counter()
print(f"elapsed time ms: {(end-start)*1000}")

elapsed time ms: 0.5362920001061866


In [31]:
import timeit, time
start = time.perf_counter()

fun(a, b, mx.gpu, mx.cpu)

end = time.perf_counter()
print(f"elapsed time ms: {(end-start)*1000}")

elapsed time ms: 0.5946669998593279
